// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telemetry.Dal;

namespace Telemetry.Dal.Migrations
{
    [DbContext(typeof(TelemetryDataContext))]
    partial class TelemetryDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Telemetry.Core.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Createdtime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Updatedtime");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Telemetry.Core.Models.DeviceData", b =>
                {
                    b.Property<int>("DeviceDataId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Createdtime");

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<int>("DeviceId");

                    b.Property<float?>("Humidity");

                    b.Property<string>("Severity")
                        .IsRequired();

                    b.Property<float?>("Temperature");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Updatedtime");

                    b.HasKey("DeviceDataId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceData");
                });

            modelBuilder.Entity("Telemetry.Core.Models.DeviceData", b =>
                {
                    b.HasOne("Telemetry.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
